apiVersion: v1
kind: Service
metadata:
  name: app-svc01
  namespace: app01
spec:
  selector:
    app: nginx
    testService: nginx-01
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30081

