apiVersion: v1
kind: Service
metadata:
  name: app-svc01
  namespace: argocd01
spec:
  selector:
    app: nginx
    testService: nginx-01
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8081
    nodePort: 30083
    protocol: TCP
